Traceback (most recent call last):
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Lenov\miniconda3\envs\geo_env_fupy\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import seaborn as sns  
import sys
sys.path.append("../src/")

from helper import cuteplot
from helper import minmax_scaler
plt.rcParams["figure.figsize"] = [22,10]
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 9[0m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m      7[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend([38;5;124m"[39m[38;5;124m../src/[39m[38;5;124m"[39m)
[1;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhelper[39;00m [38;5;28;01mimport[39;00m cuteplot
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhelper[39;00m [38;5;28;01mimport[39;00m minmax_scaler
[0;32m     11[0m plt[38;5;241m.[39mrcParams[[38;5;124m"[39m[38;5;124mfigure.figsize[39m[38;5;124m"[39m] [38;5;241m=[39m [[38;5;241m22[39m,[38;5;241m10[39m]

[1;31mModuleNotFoundError[0m: No module named 'helper'

